# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Logan CS Sharing
tagline:          'A Jekyll theme'
description:      '分享自己在CS的所學知識'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Hermes'
  url:            https://www.facebook.com/Loganning7

paginate:         5
timezone:         Asia/Taipei
# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
